version: '3.1'

services:
  mariadb1:
    container_name: mariadb1
    image: mariadb
    ports:
      - 38080:3808
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
    restart: always
    networks:
      - backend
    volumes:
      - ~/data/mariadb1:/var/lib/mysql

  mariadb2:
    image: mariadb
    container_name: mariadb2
    ports:
      - 38090:3808
    environment:
      MARIADB_ROOT_PASSWORD: mypassword
    restart: always
    networks:
      - backend
    volumes:
      - ~/data/mariadb2:/var/lib/mysql

  php1:
    build: ./requirements/php1
    container_name: php1

    networks:
      - backend
    depends_on:
      - mariadb1

  php2:
    build: ./requirements/php2
    container_name: php2
    networks:
      - backend
    depends_on:
      - mariadb2

  site01:
    image: httpd:alpine
    container_name: site01
    networks:
      - frontend
    depends_on:
      - mariadb1
      - php1
    volumes:
    - ./requirements/site01/html:/usr/local/apache2/htdocs/

  site02:
    image: httpd:alpine
    networks:
      - frontend
    depends_on:
      - mariadb2
      - php2
    volumes:
    - ./requirements/site02/html:/usr/local/apache2/htdocs/

  nginx:
    build: ./requirements/nginx
    depends_on:
      - mariadb1
      - mariadb2
    ports:
      - 8080:80
    restart: always
    networks:
      - frontend
    volumes:
        - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
        - ./requirements/site01/html:/usr/share/nginx/html/site01.com
        - ./requirements/site02/html:/usr/share/nginx/html/site02.com

networks:
  frontend:
  backend:
